### ISSUE TITLE
failed to read message length: read tcp

### ISSUE THREAD

**Issue by sahmadiut** [Musixal/Backhaul#11]
با سلام. در نسخه 0.1.3 با این خطا مواجه میشم بعد از چند دقیقه و با restart کردن تونل مشکل حل میشه. با نصب نسخه قبلی مشکلم حل شد.

12-Sep 12:59:16 [ERROR] error receiving channel signal, restarting client
12-Sep 12:59:16 [INFO] restarting client...
12-Sep 12:59:18 [INFO] trying to establish a new control channel connection
12-Sep 12:59:20 [ERROR] Failed to receive control channel response: failed to read message length: read tcp 157.230.30.39:50804->85.9.121.18:2087: i/o timeout
12-Sep 12:59:21 [INFO] trying to establish a new control channel connection
12-Sep 12:59:23 [ERROR] Failed to receive control channel response: failed to read message length: read tcp 157.230.30.39:50820->85.9.121.18:2087: i/o timeout

**Comment by Musixal** [comment]
سلام. کانفیگ دو کلاینت و سرور رو ارسال کنید.

**Comment by sahmadiut** [comment]
[client]
remote_addr = "85.9.121.18:2087"
transport = "tcp"
token = "85.9.121.18-token"
nodelay = true
retry_interval = 1
mux_session = 1
log_level = "info"




[server]
bind_addr = "0.0.0.0:2087"
transport = "tcp"
token = "85.9.121.18-token"
nodelay = true
channel_size = 2048
connection_pool = 8
mux_session = 1
log_level = "info"
sniffer = true
web_port = 2060
sniffer_log = "backhaul.json"

ports = [
    "2096=2096",
   # and other ports
]

البته تعداد پورت‌های زیادی دارم ولی نسخه قبلی بکهال با پورت زیاد مشکلی نداشتم

**Comment by Musixal** [comment]
با تنظیمات شما تست کردم مشکلی نبود. پورت کانفیگ هم ربطی به ارروی که فرستادید نداره.
