### ISSUE TITLE
اختلال سرویس ها روی سرور اصلی

### ISSUE THREAD

**Issue by Hamed2211** [Musixal/Backhaul#12]
با سلام
من چنتا کلاینت رو میخام به سرور اصلی تانل کنم تا روی سنایی لودبالانسر استفاده کنم ولی بیشتر از 2 سرویس میسازم ارور میخوره و سرویس دوم به بعد اجرا نمیشه همون دوتا سرویس هم که اجرا میشه بعد از چند دقیقه اختلال دارن و دیگه کار نمیکنن عملا یک سرویس روی سرور اصلی میشه ایجاد کرد لطفا این مورد رو بررسی کنید

این مورد رو هم بگم که با پورت ها و توکن متفاوت انجام دادم

**Comment by Hamed2211** [comment]
این مورد رو هم بگم که با پورت ها و توکن متفاوت انجام دادم

**Comment by Musixal** [comment]
سلام. به دلیل این که لاگ و کانفیگ رو نفرستادید مشکل شما قابل بررسی نیست. موضوع بسته میشه.
