### ISSUE TITLE
ChatGPT

### ISSUE THREAD

**Issue by netsupcloud** [Musixal/Backhaul#13]
سلام شما هر کدی میزنی یبار بزن تو چت جی بی تی ببین نظرش چیه من هر صفحه رو میزنم یه ایراد میگیره ازش مثلا قسمت http.server میگه خودش همزمانی اجرا داره لازم به اضافه کردن go نیست

با تشکر

**Comment by Musixal** [comment]
سلام
اگر تغییراتی مدنظر دارید از طریق PR عمل کنید.
