### ISSUE TITLE
add ability to use edge ip for cdn

### ISSUE THREAD

**Issue by AminAsa1** [Musixal/Backhaul#14]
add ability to use edge ip for cdn

**Comment by Musixal** [comment]
سلام

فایده ی این کار چیه؟‌  برای اتصال کلاینت به CDN میشه از یک آیپی خاص استفاده کرد. اما آيپی اتصال CDN به سرور  رو نمیشه تغییر داد.

**Comment by AminAsa1** [comment]
سلام
ببینید بطور مثال شما وقتی دامنه رو میبرید پشت cdn کلادفلر 4 تا ip بهش میده 2 تا v4 و 2 تا v6 در دیتاسنتر اروان  تانل ws cdn با همون ip های لبه پیشفرض به خوبی برقرار میشه ولی در بعضی دیتاسنتر ها اون رنجا بلاکه ،درصورتی که با روش تانل پنل به پنل با کانفیگ vless ws cdn با ip لبه کاستوم اکی میشه.
الان میشه از ip لبه کاستوم استفاده کرد ؟ یا اگر نمیشه خیلی ممنون میشم اضافه کنید.
با تشکر از زحماتتون

**Comment by netsupcloud** [comment]
اره جالب میشه ای پی cf رو میزنیم یا رنج ای پی cf میدیم قسمت remoteaddr کلاینت ولی باید sni ست بشه برای tls و request header host برای non-tls

**Comment by Musixal** [comment]
در روش ریورس سرور خارج به ip edge وصل میشه کلادفلر و کلادفلر با IP که خودش تعیین میکنه وصل میشه سرور ایران. هیچ وقت روی سرور خارج من ندیدم رنج خاصی از کلادفلر محدود شده باشه. موضوع بسته میشه.
