### ISSUE TITLE
Logs Says No backhaul.json File

### ISSUE THREAD

**Issue by jaafar-c** [Musixal/Backhaul#15]
Hello there, 
Thank you so much for the amazing improvments
I had this error:
```
Sep 16 14:04:29 tunnel backhaul[4969]: 16-Sep 14:04:29 [ERROR] error opening JSON file: %vopen backhaul.json: no such file or directory
Sep 16 14:04:32 tunnel backhaul[4969]: 16-Sep 14:04:32 [ERROR] error opening JSON file: %vopen backhaul.json: no such file or directory
Sep 16 14:04:35 tunnel backhaul[4969]: 16-Sep 14:04:35 [ERROR] error opening JSON file: %vopen backhaul.json: no such file or directory
```
I tried to fix it by creating a file in the root directory myself and named it backhaul.json, but I still got another error: 
`Sep 16 13:55:41 tunnel backhaul[4786]: 16-Sep 13:55:41 [ERROR] error decoding JSON data: %vEOF `

Please do tell me how to fix it
Appreciate it

**Comment by Musixal** [comment]
سلام
نیازی نیست شما فایل بسازید. کافیه در قسمت
‍`sniffer_log = "/root/backhaul.json`

رو وارد کنید. هم path و هم اسم فایل قابل تغییر است.
