### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by netsupcloud** [Musixal/Backhaul#18]
سلام

منتظر grpc هستیم وبسوکت 50 تا نرم افزار دیگه هست براش حتی با rust و c هم موجوده که سریعترن ولی اختلال دارن ولی grpc طبیعتا fingerprint کمتری داره و اکثر مواقع بهتر جواب میده

مخصوصا اگر بشه ترافیک udp عبور داد که عالی میشه

**Comment by Musixal** [comment]
سلام. gRPC بر بستر HTTPv2 ترافیک رو عبور میده. به نظرم که فعلا نیازی بهش نیست.
