### ISSUE TITLE
convert heartbeat to noise (randomized interval of heartbeat)

### ISSUE THREAD

**Issue by netsupcloud** [Musixal/Backhaul#19]
سلام بهتره مثله خود xray بجای heartbeat از noise استفاده کنید تا pattern یابیش سخت تر بشه برای dpi

  "noises":[
  {
    "type":"base64",
    "packet":"7nQBAAABAAAAAAAABnQtcmluZwZtc2VkZ2UDbmV0AAABAAE=",
    "delay":"10-16"
  }

**Comment by netsupcloud** [comment]
البته خود پکت هم بهتره randomize بشه

**Comment by Musixal** [comment]
سلام. بکهال فعلا بتا هست و باید stability بهبود پیدا کنه. بعد میشه به این چیزا فکر کرد.
