### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by SoroushImanian** [Musixal/Backhaul#2]
سلام وقتتون بخیر
خیلی بهتر میشه اگه یک ویدیو یا نحوه کانفیگ هم با جزعیات بیشتر قرار بدید برای افراد تازه کار
من خودم مشکلی نداشتم ولی خب اگه سخت باشه کمتر کسی میاد سمتش 
البته این نظر من بود

خیلی ممنون از همه چی

**Comment by ali6043** [comment]
دوست عزیز ادمای عادی که دنبال این اسکریپتا نمیان اکثرا کسانی که فروش دارن این اسکریپتا رو استفاده میکنن ،بزار حداقل کسی که میخواد ازش پول دربیاره یه زحمتی بکشه

**Comment by erfjab** [comment]
> دوست عزیز ادمای عادی که دنبال این اسکریپتا نمیان اکثرا کسانی که فروش دارن این اسکریپتا رو استفاده میکنن ،بزار حداقل کسی که میخواد ازش پول دربیاره یه زحمتی بکشه 

 Nice 🤌

**Comment by nightday1243** [comment]
فروشنده ای که همچین چیزی راحتی رو سخت بدونه بره پنل آماده بگیره یا کلا فروش رو بزاره کنار

**Comment by nightday1243** [comment]
> دوست عزیز ادمای عادی که دنبال این اسکریپتا نمیان اکثرا کسانی که فروش دارن این اسکریپتا رو استفاده میکنن ،بزار حداقل کسی که میخواد ازش پول دربیاره یه زحمتی بکشه

بی زحمت امکانش هست بخش مولتی سرور هم به هسته و دستورات اضافه کنید و یه موردی که هست در صورت که ایپی خارج فیلتر باشه tcp جواب نمیده و یا باید tcpmux باشه یا  ws  بین این 3 تا کدوم پروتکل سرعت بیشتری رو میتونه انتقال بده اگه tcp هست ممنون میشم برای ایپی های فیلترم اوکیش کنید

**Comment by Musixal** [comment]
> > دوست عزیز ادمای عادی که دنبال این اسکریپتا نمیان اکثرا کسانی که فروش دارن این اسکریپتا رو استفاده میکنن ،بزار حداقل کسی که میخواد ازش پول دربیاره یه زحمتی بکشه
> 
> بی زحمت امکانش هست بخش مولتی سرور هم به هسته و دستورات اضافه کنید و یه موردی که هست در صورت که ایپی خارج فیلتر باشه tcp جواب نمیده و یا باید tcpmux باشه یا ws بین این 3 تا کدوم پروتکل سرعت بیشتری رو میتونه انتقال بده اگه tcp هست ممنون میشم برای ایپی های فیلترم اوکیش کنید

ریورس تانل هست و روی IP فیلتر هم جواب میده. مولتی سرور رو هم میتونید با اجرای چند سرویس انجام بدید.

**Comment by Musixal** [comment]
پاسخ داده شد.
