### ISSUE TITLE
متوقف کردن سرویس

### ISSUE THREAD

**Issue by sahmadiut** [Musixal/Backhaul#22]
سلام. آیا راهی وجود داره که سرویس بکهال در صورتی که n ساعت یا دقیقه وصل نبود به صورت stop و disable بشه؟ سعی کردم با استفاده از بررسی اتوماتیک لاگ‌ها این کار رو انجام بدم ولی خیلی سخت بود. آیا فلگی چیزی وجود داره که با چک کردن اون در سرور خارج متوجه قطع بودن سرویس بشم و سرویس رو حذف کنم؟

**Comment by Musixal** [comment]
سلام. با اسکریپت bash یه سرویس ping بسازید.
