### ISSUE TITLE
مالتی سرور

### ISSUE THREAD

**Issue by hamedm311** [Musixal/Backhaul#24]
با سلام
ابتدا تشکر میکنم از شما بابت زحمات زیادتون
چه طور میشه یک سرور خارج داشت و به چند سرور ایران متصل بشه 
میدونم به روش عادی نمیشه ولی اگر راهکاری داره بفرمایید 
سپاس از شما

**Comment by Musixal** [comment]
سلام. چندین سرویس متفاوت بسازید.
