### ISSUE TITLE
مشکل مصرف رم

### ISSUE THREAD

**Issue by alirezamobile99** [Musixal/Backhaul#25]
وقت بخیر . نسخه 0.4.0 مشکل مصرف رم داره هرچی میگذره مصرف رم میره بالاتر تا جایی که سرور کرش کنه

**Comment by alirezamobile99** [comment]
client :

transport = "wsmux"             
token = "alireza"          
keepalive_period = 75         
connection_pool = 8
nodelay = false               
channel_size = 2048
retry_interval = 1            
mux_con = 8
mux_version = 2
mux_framesize = 32768         
mux_recievebuffer = 4194304  
mux_streambuffer = 65536



server :

transport = "wsmux"             
token = "alireza"     
keepalive_period = 75       
nodelay = false               
mux_con = 8
mux_version = 2             
mux_framesize = 32768         
mux_recievebuffer = 4194304  
mux_streambuffer = 65536      

ports = [ 
    "1315",
"86",
]

از سمت کلاینت یا همون سرور خارج این مشکل هست

**Comment by alirezamobile99** [comment]
موارد زیر هم وارد نکردم هر دو طرف : 
sniffer = false 
web_port = 2060
sniffer_log = "/root/backhaul.json"
log_level = "info"

**Comment by Musixal** [comment]
سلام
نسخه 0.4.1 رو نصب کنید. فکر میکنم مشکل memory leak حل شده باشه.

**Comment by Musixal** [comment]
مقادیر tcp buffer رو هم تنظیم کنید. مقادیر پایین تری در sysctl بذارید:

net.ipv4.tcp_rmem = 4096 32768 2097152
net.ipv4.tcp_wmem = 4096 32768 2097152

**Comment by alirezamobile99** [comment]
تمام مواردی که فرمودید انجام شد ولی هنوز همون مشکل هست

**Comment by Musixal** [comment]
اگر ورژن 0.4.1 نصب کردید مشکل لیک مموری حل شده ولی دلیل مصرف بالاتر مموری io.Copy و بافر 32KB هست که استفاده می کنه. تو نسخه بعد اصلاح میکنم.

**Comment by alirezamobile99** [comment]
اوکی ممنون

**Comment by alirezamobile99** [comment]
لطفا در صورت امکان داخل صفحه اصلی پروژه ، توضیحات مربوط به تنظیم دقیق پارامتر های مختلف مثل channel size , connection pool و موارد دیگه رو قرار بدید که هرکسی بسته به تعداد یوزر ها و ترافیک عبوری تانل بتونه مقادیر دقیق رو تعیین کنه . توضیحات استفاده از اسکریپت های optimizer هم قرار بدید بی زحمت عالی و کامل میشه

**Comment by alirezamobile99** [comment]
تانل من روی نسخه 0.5.1 بیشتر از ششصد مگابیت رم مصرف میکنه تا جایی که سرور کرش کنه . تمام مواردی هم که گفته بودید انجام شده ولی تغییری نکرده

**Comment by Musixal** [comment]
سلام. نسخه آخر رو تست کنید. کانفیگ دقیق رو هم باید ذکر کنید.
