### ISSUE TITLE
بررسی ارور ها

### ISSUE THREAD

**Issue by alirezamobile99** [Musixal/Backhaul#28]
وقت بخیر . ارور پیوست شده به چه دلیل میتونه باشه ؟ بکهال 0.4.1
![v1](https://github.com/user-attachments/assets/cd86cc8c-fa3b-4efb-8532-7a76ccc1f5a0)

**Comment by Musixal** [comment]
سلام
یکی مربوط به ریستارت سرویس در سرور دیگه است. یکی دیگه هم مربوط به اختلالات دیتاسنتر هست. برنامه در این موارد سعی میکنه کانکشن رو ریکاور کنه.

**Comment by alirezamobile99** [comment]
درسته منم حدس زدم از سمت دیتاسنتر ایران باشه

**Comment by Musixal** [comment]
اگر روی کلاد استفاده میکنید از hearbeat پایین تری ست کنید. ورژن 0.4.2 رو هم بزنید

**Comment by alirezamobile99** [comment]
تشکر . فقط اینکه من روی سرور V2RAY از کانفیگ VLESS WS خالی استفاده میکنم پیشنهادی دارید برای پرفورمنس بهتر ؟

**Comment by alirezamobile99** [comment]
مورد بعدی اینکه من کلا از HEARTBEAT استفاده نمیکنم . با توجه به اینکه تعداد کاربر ها روی هر سرور بالاس آیا خوبه که استفاده بشه یا خیر ؟ و اینکه اگر ممکنه داخل صفحه اصلی پروژه توضیحات مربوط به تنظیم دقیق تمام پارامتر های تانل ذکر بشه بر اساس تعداد یوزر و ترافیک عبوری در لحظه . ممنون

**Comment by alirezamobile99** [comment]
مهندس این لاگ سرور ایران آخرین نسخه بکهال 0.4.3 به نظرتون مشکلش چیه ؟
![backhaul111](https://github.com/user-attachments/assets/cf69d905-2a15-45b8-9272-56124d625be3)

**Comment by Musixal** [comment]
برای وب سوکت heartbeat حدود ۴۰ ثانیه نیازه. لاگ های error مربوط به mux هم مشکلی ایجاد نمیکنه ولی درصدد بهبودش هستم
