### ISSUE TITLE
ریورس بر بستر cdn

### ISSUE THREAD

**Issue by myroya122** [Musixal/Backhaul#3]
با سلام من میخوام با سی دی ان رو تست کنم
اما وقتی پروکسی کلودفلر رو روشن میکنم
ارتباط قطع میشه فقط ساب دامنه ایرانو گذاشتم تو خارج و اینکه وب سوکت هم هست استارت ک میزنم تو خارج این میاد 06-Sep 05:25:16 [INFO] client with remote
address test.***.***:2057 started successfully
Sep 06 05:25:16 TEST backhaul[37210]: 06-Sep 05:25:16 [INFO] trying to establish a new ws control channel connection

**Comment by Musixal** [comment]
سلام. احتمالا یه جایی رو اشتباه رفتید یا تنظیمات کلادفلر درست نیست.
