### ISSUE TITLE
نحوه تست

### ISSUE THREAD

**Issue by hamedkhorasani** [Musixal/Backhaul#30]
من ارتباط بین دو سرور ایران و خارج رو انجام دادم. الان میخوام از سرور ایران تست کنم که آیا به سایت های فیلتر شده دسترسی دارم یا نه. چجوری باید تست انجام بدم؟

**Comment by prsgh** [comment]
از چه کانفیگ، پنل یا پروتکلی میخواید برای اتصال استفاده کنید؟

**Comment by Musixal** [comment]
سلام. یوتیوب رو چک کنید یه سری آموزش دادم.
