### ISSUE TITLE
channel size

### ISSUE THREAD

**Issue by alirezamobile99** [Musixal/Backhaul#31]
![channel](https://github.com/user-attachments/assets/e9dbf9ec-4e6f-4ed9-b0ad-9329de241a80)
وقت بخیر . برای حدود 1000 تا کاربر channel size روی چند باشه ؟

**Comment by Musixal** [comment]
سلام. بستگی چه تعداد کانکشن روی سرورتون میاد. عدد 8192 بذارید. اگر channel پر شه یعنی pool size کمه یا ارتباط تانل قطع شده. pool size = 256 رو تست کنید.

**Comment by alirezamobile99** [comment]
منظورتون از pool size همون connection_pool  هست ؟

**Comment by Musixal** [comment]
بله

**Comment by alirezamobile99** [comment]
![Untitleddf](https://github.com/user-attachments/assets/78733464-313d-4947-b94c-c196b8177a33)

این به چه علت هست که هی ریست میکنه خودشو ؟

**Comment by alirezamobile99** [comment]
تنظیمات سرویس :

[Unit]
Description=Backhaul Reverse Tunnel Service
After=network.target

[Service]
Type=simple
ExecStart=/root/newbackhaul/./backhaul -c /root/newbackhaul/server1010.toml
Restart=always
RestartSec=3
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target

**Comment by alirezamobile99** [comment]
تنظیمات فایل toml سرور

bind_addr = "0.0.0.0:5050"    # Address and port for the server to listen on (mandatory).
transport = "wsmux"             # Protocol to use ("tcp", "tcpmux", "ws", "wss", "wsmux", "wssmux". mandatory).
token = "alireza"          # Authentication token for secure communication (optional).
keepalive_period = 75         # Interval in seconds to send keep-alive packets.(optional, default: 20 seconds)
nodelay = false               # Enable TCP_NODELAY (optional, default: false).
channel_size = 8192
pool_size = 256
heartbeat = 40
mux_con = 8
mux_version = 1               # TCPMux protocol version (1 or 2). Version 2 may have extra features. (optional)
mux_framesize = 32768         # 32 KB. The maximum size of a frame that can be sent over a connection. (optional)
mux_recievebuffer = 4194304   # 4 MB. The maximum buffer size for incoming data per connection. (optional)
mux_streambuffer = 65536      # 256 KB. The maximum buffer size per individual stream within a connection. (optional)

ports = [
"85",
"2086",
]

**Comment by alirezamobile99** [comment]
حتی سرور ایران یکبار تغییر کرد ولی باز فرقی نکرده

**Comment by alirezamobile99** [comment]
یکبار هم شماره پورت تغییر کرده ولی فرقی نکرد
