### ISSUE TITLE
خطا هنگام اجرا

### ISSUE THREAD

**Issue by rezhacker** [Musixal/Backhaul#32]
سلام. من توی سرور ایرانم با ورژن 4.4 این خطا رو دارم. مشکل از چیه؟ کانکشن از نوع tcp ساده است

![Untitled](https://github.com/user-attachments/assets/d7e00ebc-3494-47c6-9a53-aebb711eecfc)

**Comment by rezhacker** [comment]
قبل از این ورژن 3.3 رو داشتم با همین فایل کانفیگ این خطا رو نداشتم. مسیر فایل جیسون هم بهش دادم. فایل هم ایجاد کردم

**Comment by eylandoo** [comment]
برادر فایل کانفیگت رو طبق گیت‌هاب بزن  چنتا آپشن کم داره اونارو ک بزنی به فایل کانفیگت حل میشه

**Comment by rezhacker** [comment]
فایل کانفیگ سرور و کلاینت من دقیقا مشابه نمونه گذاشته شده توی گیت هاب هست
[server]
bind_addr = "0.0.0.0:3080"
transport = "tcp"
token = "your_token"
keepalive_period = 75  
nodelay = true 
heartbeat = 40 
channel_size = 2048
sniffer = false 
web_port = 2060
sniffer_log = "/root/backhaul.json"
log_level = "info"
ports = []

[client]
remote_addr = "0.0.0.0:3080"
transport = "tcp"
token = "your_token" 
connection_pool = 8
keepalive_period = 75
dial_timeout = 10
nodelay = true 
retry_interval = 3
sniffer = false
web_port = 2060 
sniffer_log = "/root/backhaul.json"
log_level = "info"

**Comment by Musixal** [comment]
سلام. ورژن آخر رو تست کنید.

**Comment by celeverhkp** [comment]
سلام داداش ، ممنون بابت همه چی ، من یک مشکلی ، همه‌چیز اوکیه کانفیگ ها همه به درستی کار میده فقط وقتی ای پی ایران رو توی cdn کلودفلر ست میکنم و از دامین بجای ای پی ایران استفاده میکنم دیگه پینگ ندارم و اسپید تست که میزنم کرش میشه برنامه ، البته با وجود اینکه توی برنامه کلاینت مثل v2rayNg پینگ ندارم اما اینستاگرام و تلگرام بدون مشکل کار می‌کنه فقط تست پینگ که میزنم -1 میاد ، من از پروتکل tcp ساده و ورژن 4.5 بکهال استفاده کردم 🙏
