### ISSUE TITLE
مشکل در پورت مپ کردن و اجرا نشدن سرویس بک هال

### ISSUE THREAD

**Issue by lvlrf** [Musixal/Backhaul#33]
درود ارادت عرض ادب

من وقتی به صورت زیر تنظیمات پورت رو وارد میکنم بک هال اجرا نمیشه و خطا میده :

```
ports = [
        "5201",
        "1701=116.203.6.243:1701",
        "500=116.203.6.243:500",
        "58=116.203.6.243:58",
        "17=116.203.6.243:17",
        "50=116.203.6.243:50",
        "115=116.203.6.243:115",
        "4500=116.203.6.243:4500",
        "50=116.203.6.243:50"
]
```

فایل کانفیگ سرورم :

[server]
bind_addr = "0.0.0.0:3080"
transport = "tcp"
token = "your_token"
keepalive_period = 75
nodelay = true
heartbeat = 40
channel_size = 2048
sniffer = true
web_port = 2060
sniffer_log = "/root/backhaul.json"
log_level = "info"
ports = [
        "5201",
        "1701=116.203.6.243:1701",
        "500=116.203.6.243:500",
        "58=116.203.6.243:58",
        "17=116.203.6.243:17",
        "50=116.203.6.243:50",
        "115=116.203.6.243:115",
        "4500=116.203.6.243:4500",
        "50=116.203.6.243:50"
]
و فایل کانفیگ کلاینتم :

```
[client]
remote_addr = "84.47.235.173:3080"
transport = "tcp"
token = "your_token"
connection_pool = 8
keepalive_period = 75
dial_timeout = 10
nodelay = true
retry_interval = 3
sniffer = true
web_port = 2060
sniffer_log = "/root/backhaul.json"
log_level = "info"

```

این خطایی بود که میداد :
**خطا یک**
`
[ERROR] failed to dial tunnel server: failed to dial TCP address 84.47.235.173:3080 after 3 retries: dial tcp 84.47.235.173:3080: connect: connection refused
11-Oct 08:24:46 [ERROR] failed to dial tunnel server: failed to dial TCP address 84.47.235.173:3080 after 3 retries: dial tcp 84.47.235.173:3080: connect: connection refused
11-Oct 08:24:48 [INFO] attempting to establish a new control channel connection...
11-Oct 08:24:48 [INFO] sniffer service listening on port: :2060
11-Oct 08:24:53 [ERROR] failed to receive control channel response: failed to read message length from net.Conn: read tcp 5.75.193.65:30298->84.47.235.173:3080: i/o timeout
11-Oct 08:24:58 [ERROR] failed to receive control channel response: failed to read message length from net.Conn: read tcp 5.75.193.65:30300->84.47.235.173:3080: i/o timeout  

آی پی که توش این هستش آی پی سرور کلاینت هستش

`

**خطا دو**
`channel dialer: error dialing remote address ****** : failed to dial TCP address****** after 3 retries: dial tcp***** : connect: connection refused
`

1.
گفتم شاید مشکل این ورژن باشه چون طبق داکیومنت پورت ها رو وارد کردم
ServerBackhaul.IPListen:Port=ClientBackhaul.IPListen=Port
به این صورت دیدم بود ساختار درسته؟

2.
خطا حالت اول برای زمانی هست که سرور ایرانA سرور بک هال -> سرور خارج B کلاینت بک هال -> و میخواستم پورت های تعریف شده در تانل بک هال از کلاینت سمت سرور خارج B به سمت سرور شماره خارج C بره دیتا هاو دریافت کنه.

3.
خطا شماره دو برای زمانی هستش که سرور ایرانA سرور بک هال -> سرور خارج B کلاینت بک هال هستش و سرور شماره B یک کانتینر تو دل میکروتیک هستش و پورت ها به جای ارسال به آی پی پابلیک به آی پی پرایوت میکروتیک از سمت کانتینرش میرفت که پینگ و ارتباط برقرار بود اما سرویس بک هال با این پورت مپینگ اجرا نمیشد.

4.
میشه یه رنج پورت داد و اونارو فوروارد کرد؟ مثلا بگم پورت های 100-200 رو بگیر همونو بده به خارج روی همون پورت انتقال داد؟

5.
میشه ترافیک UDP روی بک هال گذروند؟ با ترنسمیشن های TCP یا WS ?

6.
ای کاش بابت یه سری پارامتر ها آموزشی مثل ویدئو هایی که درست کردید میدادید که بدونیم با توجه به حجم درخواست ها ترافیک یا ... چطور باید پارامتر ها رو بهینه کنیم؟ مثل channel_size  و ...

**Comment by assasinscreed74** [comment]
ports = [
        "5201",
        "1701=1701",
        "500=500",
        "58=58",
        "17=17",
        "50=50",
        "115=115",
        "4500=4500",
        "50=50",
]

**Comment by Musixal** [comment]
تست کردم، فوورادر بکهال مشکلی نداره. این که شما داخل کانتینر میکروتیک رو اجرا کردید شاید باعث مشکل باشه. به حال issue شما فراتر از بکهال است.
