### ISSUE TITLE
ریستارت شدن سرویس از سمت سرور هر پنج دقیقه

### ISSUE THREAD

**Issue by alirezamobile99** [Musixal/Backhaul#34]
![backhaul](https://github.com/user-attachments/assets/3f71754b-f395-49cc-b160-f9f446d214d6)
وقت بخیر من روی چند تا سرور بکهال دارم و روی همشون این مشکل رو دارم که تند تند دارن ریست میشن از سمت سرور 
نسخه : 0.4.5

**Comment by alirezamobile99** [comment]
تنظیمات سرویس :

[Unit]
Description=Backhaul Reverse Tunnel Service
After=network.target

[Service]
Type=simple
ExecStart=/root/newbackhaul/./backhaul -c /root/newbackhaul/server1010.toml
Restart=always
RestartSec=3
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target

**Comment by alirezamobile99** [comment]
تنظیمات فایل toml سرور

bind_addr = "0.0.0.0:5050" # Address and port for the server to listen on (mandatory).
transport = "wsmux" # Protocol to use ("tcp", "tcpmux", "ws", "wss", "wsmux", "wssmux". mandatory).
token = "alireza" # Authentication token for secure communication (optional).
keepalive_period = 75 # Interval in seconds to send keep-alive packets.(optional, default: 20 seconds)
nodelay = false # Enable TCP_NODELAY (optional, default: false).
channel_size = 8192
heartbeat = 40
mux_con = 8
mux_version = 1 # TCPMux protocol version (1 or 2). Version 2 may have extra features. (optional)
mux_framesize = 32768 # 32 KB. The maximum size of a frame that can be sent over a connection. (optional)
mux_recievebuffer = 4194304 # 4 MB. The maximum buffer size for incoming data per connection. (optional)
mux_streambuffer = 65536 # 256 KB. The maximum buffer size per individual stream within a connection. (optional)

ports = [
"85",
"2086",
]

**Comment by alirezamobile99** [comment]
حتی سرور ایران یکبار تغییر کرد ولی باز فرقی نکرده
یکبار هم شماره پورت تغییر کرده ولی فرقی نکرد

**Comment by alirezamobile99** [comment]
روی نسخه های قبلی بکهال هم مشکل داشتم

**Comment by Musixal** [comment]
لینوکس سرویس شما رو kill میکنه. لاگ دقیق رو باید با journalctl ببینید که دلیلش چیه.

**Comment by alirezamobile99** [comment]
با افزایش رم سرور ایران از یک گیگ به دو گیگ مشکل رفع شد
