### ISSUE TITLE
channel with listener is full

### ISSUE THREAD

**Issue by ahmad0489** [Musixal/Backhaul#35]
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:49:41 nnn backhaul[2494]: 13-Oct 23:49:41 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>
Oct 13 23:50:27 nnn backhaul[2494]: 13-Oct 23:50:27 [WARNING] channel with listener [::]:44408 is full, discarding TCP connection from 79.175.162.>

برای من هر چند ساعت این ارور میاد با اینکه کانکشن پول هم افزایش دادم همچنان مشکل پابرجاست

**Comment by ahmad0489** [comment]
چجوری میشه مشکل رو رفع کرد؟

**Comment by ahmad0489** [comment]
تا وقتی که سرویسی که روی سرور ایران ساختم رو ریستارت نمیکنم هم درست نمیشه

**Comment by Musixal** [comment]
Log + Config

**Comment by ahmad0489** [comment]
حقیقتا من هرچی تلاش کردم لاگی ایجاد نشد که بفرستم ولی فایل کانفیگ به این صورته
[client]
remote_addr = "doamin.com:443"
transport = "wss"
token = "token" 
connection_pool = 128
keepalive_period = 75
dial_timeout = 10
retry_interval = 3  
nodelay = true 
sniffer = true 
sniffer_log = "/root/backhaul.json"
log_level = "info"

[server]
bind_addr = "0.0.0.0:443"
transport = "wss"
token = "token" 
channel_size = 2048
heartbeat = 3 
keepalive_period = 75 
nodelay = true 
tls_cert = "/root/cert.crt"      
tls_key = "/root/private.key"
sniffer = true 
sniffer_log = "/root/backhaul.json"
log_level = "info"
ports = [
"2005=2005",
]

**Comment by alirezamobile99** [comment]
برای منم باز اینطوری میشه کاش میشد یه حرکتی زد که دیگه تحت هیچ شرایطی این مشکل پیش نیاد

**Comment by Musixal** [comment]
ورژن آخر رو تست کنید فکر میکنم مشکل ریستارت حل شده باشه. چنل سایز رو بالاتر ببرید مثل ۸۱۹۲. اگر هم چنان پیام فول شدن مشکل از ارتباط خارج به داخل است. هم چنین لاگ خارج رو هم علی رغم تاکید ارسال نکردید.
