### ISSUE TITLE
مشکل بالا رفتن پینگ و کاهش سرعت

### ISSUE THREAD

**Issue by ahmad0489** [Musixal/Backhaul#36]
در نسخه اخر یعنی 4.5.1 بعد از چند ساعت پینگ به شدت میره بالا و به 2000 - 3000 میرسه و سرعت هم میاد پایین، با ریستارت کردن سرویس مشکل حل میشه

چک کردم هر دو سرور رو نه رم پر بود و نه سیپیو بالا رفته بود احتمال داره که مشکل از چی باشه؟

**Comment by rezhacker** [comment]
این مشکل رو منم دارم. توی ورژن 0.3.3 اصلا این اشکال رو نداشتم و سرعت خوب بود. کانکشن از نوع tcp ساده است. کلا هم 10 تا یوزر وصل هستن

**Comment by Musixal** [comment]
بدون لاگ و کانفیگ هر دو سرور کمکی نمیشه کرد. منم شخصا این مشکل رو نداشتم.
