### ISSUE TITLE
تاخیر در ارسال پیام در واتزاپ

### ISSUE THREAD

**Issue by gghkp** [Musixal/Backhaul#37]
با سلام و قدردانی بابت زحماتی که می کشید، من تانل بکهال رو بین سرور ایران و خارج برقرار کردم و به خوبی کار می کنه، تنها مشکلی که دارم اینه که وقتی توی واتزاپ پیام ارسال می کنم، پیام ها با تاخیر ارسال میشه.
ممنون میشم اگه راهنمایی فرمائید
![photo_2024-10-16_12-14-27](https://github.com/user-attachments/assets/649e23e4-d4c2-45e0-803c-ee48bdf6b51c)
![photo_2024-10-16_12-14-27](https://github.com/user-attachments/assets/e6aaf0e4-32c5-4414-90cd-a495fd482866)

**Comment by Musixal** [comment]
مربوط به بکهال نیست و به کانفیگ هست. vless tcp header استفاده کنید یا کانفیگ دیگه ای رو تست بفرمایید.
