### ISSUE TITLE
retry

### ISSUE THREAD

**Issue by alirezamobile99** [Musixal/Backhaul#42]
وقت بخیر . چطور میشه تنظیم کرد که کلاینت به سمت سرور دائم در حال تلاش برای اتصال باشه و اینطوری نباشه که پس از چندین بار تلاش ناموفق کلا دیگه retry نکنه ؟
![Uploading retry.jpg…]()

**Comment by alirezamobile99** [comment]
![retry](https://github.com/user-attachments/assets/bc0b2436-d879-4dd7-b97e-2a62083f7c4b)

**Comment by Musixal** [comment]
سلام. نمیدونم منظورتون چیه ولی هر کانکشن اگر بیشتر از ۳ بار retry متصل نشد discard میشه. بیشتر از این مقدار منطقی نیست.

**Comment by alirezamobile99** [comment]
منظور اینکه مثلا سرور ایران از دسترس خارج شده ، از سمت کلاینت که همون سرور خارج هست اینقدر تلاش کنه و retry کنه که هروقت سرور ایران دوباره در دسترس شد تانل برقرار باشه و نیاز نباشه دستی تانل رو ریستارت کنیم از سمت کلاینت تا مجدد کانکت بشه

**Comment by Musixal** [comment]
این چیزی که میفرمایید رو بکهال همون ورژن اولیه هم داشت.
