### ISSUE TITLE
network usage

### ISSUE THREAD

**Issue by mohsenabedi-dev** [Musixal/Backhaul#44]
سلام
میخواستم بدونم در روشی که پنل ایران به عنوان مستر یعنی سرور اصلی باشه آیا در میزان مصرف ترافیک تاثیر و افزایش داره؟
این میزان افزایش چقدر است؟
نتورک ۳ برابر ترافیک را نشان میدهد

**Comment by Musixal** [comment]
تاپیک تکراری است.
