### ISSUE TITLE
مصرف

### ISSUE THREAD

**Issue by mohsenabedi-dev** [Musixal/Backhaul#45]
سلام
میخواستم بدونم در روشی که پنل ایران به عنوان مستر یعنی سرور اصلی باشه آیا در میزان مصرف ترافیک تاثیر و افزایش داره؟
این میزان افزایش چقدر است؟
نتورک ۳ برابر ترافیک را نشان میدهد!!!!

**Comment by Musixal** [comment]
سلام. شخصا تست نکردم ولی در استفاده عادی معمولا ۲۰ درصد مصرف بیش تر هست که در تقریبا در تمام تانل ها دیده میشه.

**Comment by mohsenabedi-dev** [comment]
طبق تجربه ای که داشتم ۱۲ برابر دانلود بشتری انداخته

**Comment by Musixal** [comment]
به خاطر بافر tcp هست. اسپید تست رو باید ببندید. مشکل دانلود رو هم همه ی تانل ها دارند. (فکر میکنم 6to4 اوکی باشه)
