### ISSUE TITLE
خطا tcp tunning

### ISSUE THREAD

**Issue by rezhacker** [Musixal/Backhaul#47]
من به ورژن جدید 0.6.4 آپدیت کردم. موقع اجرا برای اجرا کردن tcp tunning خطا میده. هم در سرور ایران و هم سرور خارج. تا ورژن قبلی 0.6.3 این اشکال وجود نداشت. منم تغییری توی تنظیمات ندادم.

Nov 27 05:50:10 irvm-372555 systemd[1]: Started Backhaul Reverse Tunnel Service.
Nov 27 05:50:10 irvm-372555 backhaul[53507]: 27-Nov 05:50:10 [INFO] Applying TCP optimizations for Linux...
Nov 27 05:50:10 irvm-372555 backhaul[53507]: 27-Nov 05:50:10 [ERROR] Failed to apply TCP tuning: exit status 255
Nov 27 05:50:10 irvm-372555 backhaul[53507]: 27-Nov 05:50:10 [ERROR] Failed to apply TCP tuning: exit status 255
Nov 27 05:50:10 irvm-372555 backhaul[53507]: 27-Nov 05:50:10 [INFO] server started successfully, listening on address: [::]:3080
Nov 27 05:50:10 irvm-372555 backhaul[53507]: 27-Nov 05:50:10 [INFO] sniffer service listening on port: :2060
Nov 27 05:50:11 irvm-372555 backhaul[53507]: 27-Nov 05:50:11 [INFO] control channel successfully established.
Nov 27 05:50:11 irvm-372555 backhaul[53507]: 27-Nov 05:50:11 [INFO] starting 2 handle loops on each CPU thread
Nov 27 05:50:11 irvm-372555 backhaul[53507]: 27-Nov 05:50:11 [INFO] listener started successfully, listening on address: [::]:2083
Nov 27 05:50:11 irvm-372555 backhaul[53507]: 27-Nov 05:50:11 [INFO] Round Trip Time (RTT): 100 ms

**Comment by Musixal** [comment]
سلام. چیز خاصی نیست. توی ریلیز بعدی دقیقا توی لاگ مشخص میکنم مربوط به کدوم آپشنه و اصلاحش میکنم. روی Ubuntu 22 چک کردم اوکی بود
