### ISSUE TITLE
نویز

### ISSUE THREAD

**Issue by mgod122** [Musixal/Backhaul#9]
سلام مشکلی که من رو دیتاسنترای مختلف تستش کردم باخارج های مختلف سرویس یه نویز پینگ داره از 300 400 میپره روی 1000 1500 فرقیم نمیکنه حالا سرور ایرانت کجا یاخارجت کجا باشه باتستهای که انجام دادم این مورد هستش و اینکه بعد چند ساعت پینگ کمی بالا میره انگار که نیاز به ریستارت داره با حذف و نصب تانل درست میشه

**Comment by Musixal** [comment]
سلام. بالای ۵۰ ترابایت ترافیک رد کردم و مشکل شما رو ندیدم. به علاوه هیچ اطلاعاتی هم از کانفیگ ارائه ندید. موضوع بسته میشه.
